version: '3'
services:
  app:
    image: docker-spring-boot-postgres
    ports:
      - 8080:8080
    build:
      context: .
    container_name: app
    links:
      - redis
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/vv
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      mynetwork:
        aliases:
         - app.mynetwork
  redis:
    container_name: redis
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      mynetwork:
        aliases:
          - redis.mynetwork
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qqq
      POSTGRES_DB: vv
    networks:
      mynetwork:
        aliases:
          - postgres.mynetwork
networks:
  mynetwork:
    external:
      name: myglobalnetwork